// Função auxiliar de higienização de string para os blocos de código
const codeStr = (lines) => lines.join('\n');

window.DATA_OFICINA = {
    id: 'oficina',
    title: '2. Mão na Massa',
    icon: 'fa-solid fa-laptop-code',
    content: [
        {
            type: 'card',
            title: '<i class="fa-solid fa-code-branch"></i> Desenvolvimento Orientado',
            html: '<p>Acompanhe a construção progressiva do nosso sistema. Iniciaremos preparando nossa estação de trabalho corporativa. Em seguida, desenvolveremos manualmente o "Caminho Feliz" (lógica pura sem proteções) e utilizaremos uma Inteligência Artificial como copiloto para refatorar o código, adicionar resiliência (try/except), gerar relatórios em disco e construir uma Interface Gráfica.</p>'
        },
        {
            type: 'accordion',
            items: [
                {
                    title: 'Marco Zero: Configuração do Ambiente Corporativo (CPython & VS Code)',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    GUIA DE INFRAESTRUTURA DE DESENVOLVIMENTO (Responsável: Léo)',
                        '    Objetivo: Configurar uma estação de trabalho limpa, padronizada e produtiva.',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># ETAPA 1: INSTALAÇÃO DO INTERPRETADOR OFICIAL (CPYTHON)</span>',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># 1. Acesse o portal oficial: https://www.python.org/downloads/</span>',
                        '<span class="c-comment"># 2. Baixe a versão estável mais recente (Python 3.12+).</span>',
                        '<span class="c-comment"># 3. CRÍTICO NO WINDOWS: Na primeira tela do instalador, marque obrigatoriamente</span>',
                        '<span class="c-comment">#    a caixa "Add python.exe to PATH". Se omitir isso, o sistema operacional não</span>',
                        '<span class="c-comment">#    reconhecerá os comandos \'python\' ou \'pip\' no terminal.</span>',
                        '',
                        '<span class="c-comment"># Validação no Terminal (PowerShell ou CMD):</span>',
                        'python --version',
                        '<span class="c-comment"># Saída esperada: Python 3.12.x</span>',
                        '',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># ETAPA 2: INSTALAÇÃO DA IDE (VISUAL STUDIO CODE)</span>',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># 1. Baixe o VS Code: https://code.visualstudio.com/</span>',
                        '<span class="c-comment"># 2. Durante a instalação, marque a opção "Adicionar ao PATH".</span>',
                        '',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># ETAPA 3: EXTENSÕES OBRIGATÓRIAS NO VS CODE</span>',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># Abra o VS Code, pressione Ctrl+Shift+X e pesquise/instale o pacote oficial:</span>',
                        '<span class="c-comment"># -> Nome: "Python" (Publicado pela Microsoft - ID: ms-python.python)</span>',
                        '<span class="c-comment">#    (Esta extensão ativa auto-completar, linting, formatação e debug).</span>',
                        '',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># ETAPA 4: DOMINANDO AS EXTENSÕES DE ARQUIVOS</span>',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># No mercado de tecnologia, trabalhamos primariamente com dois formatos:</span>',
                        '<span class="c-comment">#</span>',
                        '<span class="c-comment"># • Arquivos .py (Scripts de Produção):</span>',
                        '<span class="c-comment">#   Código estruturado sequencial ou modular. É o arquivo final que roda nos</span>',
                        '<span class="c-comment">#   servidores, rotinas automatizadas e empacotadores (.exe).</span>',
                        '<span class="c-comment">#</span>',
                        '<span class="c-comment"># • Arquivos .ipynb (Jupyter Notebooks):</span>',
                        '<span class="c-comment">#   Formato interativo dividido em "Células" de código e texto enriquecido.</span>',
                        '<span class="c-comment">#   Extremamente utilizado para Análise de Dados, testes rápidos de Inteligência</span>',
                        '<span class="c-comment">#   Artificial e documentação visual. Para usá-lo no VS Code, instale a</span>',
                        '<span class="c-comment">#   extensão oficial "Jupyter" (ID: ms-toolsai.jupyter).</span>'
                    ])
                },
                {
                    title: 'PMV 1.0: O "Caminho Feliz" (Execução Sequencial Pura)',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    Desenvolvimento inicial focado exclusivamente na lógica de negócio.',
                        '    Sem tratamento de erros. Se o usuário digitar texto no lugar do valor, o sistema quebra.',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-func">print</span>(<span class="c-string">"=== SISTEMA DE AUDITORIA FINANCEIRA v1.0 ==="</span>)',
                        '<span class="c-func">print</span>(<span class="c-string">"Iniciando captura de dados...\\n"</span>)',
                        '',
                        '<span class="c-comment"># 1. Entrada de Dados</span>',
                        'categoria_texto = <span class="c-func">input</span>(<span class="c-string">"Digite a categoria (transporte/alimentacao/hospedagem): "</span>)',
                        'categoria = categoria_texto.strip().lower()',
                        '',
                        'valor_texto = <span class="c-func">input</span>(<span class="c-string">"Digite o valor do gasto (R$): "</span>)',
                        'valor_formatado = valor_texto.replace(<span class="c-string">","</span>, <span class="c-string">"."</span>)',
                        '',
                        '<span class="c-comment"># 2. Conversão explícita (Casting). Ponto crítico de falha se houverem letras.</span>',
                        'valor = <span class="c-func">float</span>(valor_formatado)',
                        '',
                        '<span class="c-func">print</span>(<span class="c-string">"\\nProcessando regras de compliance..."</span>)',
                        '',
                        '<span class="c-comment"># 3. Árvore de Decisão Extensa (Lógica Repetitiva)</span>',
                        '<span class="c-keyword">if</span> valor <= 0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: NEGADO - Valor deve ser maior que zero."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"transporte"</span> <span class="c-keyword">and</span> valor <= 150.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO AUTOMATICAMENTE - Dentro do teto de transporte."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"transporte"</span> <span class="c-keyword">and</span> valor > 150.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: REQUER ANÁLISE - Ultrapassou teto de transporte."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"alimentacao"</span> <span class="c-keyword">and</span> valor <= 85.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO AUTOMATICAMENTE - Dentro do teto de alimentação."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"alimentacao"</span> <span class="c-keyword">and</span> valor > 85.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: REQUER ANÁLISE - Ultrapassou teto de alimentação."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"hospedagem"</span> <span class="c-keyword">and</span> valor <= 450.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO AUTOMATICAMENTE - Dentro do teto de hospedagem."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"hospedagem"</span> <span class="c-keyword">and</span> valor > 450.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: REQUER ANÁLISE - Ultrapassou teto de hospedagem."</span>)',
                        '<span class="c-keyword">else</span>:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: NEGADO - Categoria não reconhecida."</span>)',
                        '',
                        '<span class="c-func">print</span>(<span class="c-string">"\\nAuditoria finalizada."</span>)'
                    ])
                },
                {
                    title: 'Versão 2.0: Evolução IA - Resiliência e Tratamento de Erros',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    PROMPT ENVIADO À IA:',
                        '    "Atue como Arquiteto Python. O código do PMV 1.0 quebra se o usuário digitar',
                        '    letras no campo de valor monetário. Refatore o código adicionando blocos de',
                        '    tratamento de exceções (try/except/finally) para capturar o erro ValueError',
                        '    e impedir que o sistema feche abruptamente. Otimize levemente os condicionais."',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-func">print</span>(<span class="c-string">"=== SISTEMA DE AUDITORIA FINANCEIRA v2.0 ==="</span>)',
                        '',
                        '<span class="c-keyword">try</span>:',
                        '    categoria = <span class="c-func">input</span>(<span class="c-string">"Categoria (transporte/alimentacao/hospedagem): "</span>).strip().lower()',
                        '    valor_input = <span class="c-func">input</span>(<span class="c-string">"Valor do gasto (R$): "</span>).replace(<span class="c-string">","</span>, <span class="c-string">"."</span>)',
                        '    ',
                        '    <span class="c-comment"># Se a conversão falhar, o interpretador pula direto para o bloco except</span>',
                        '    valor = <span class="c-func">float</span>(valor_input)',
                        '    ',
                        '    <span class="c-keyword">if</span> valor <= 0:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Parecer: NEGADO - Valor inválido."</span>)',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"transporte"</span> <span class="c-keyword">and</span> valor <= 150.0:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO"</span>)',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"alimentacao"</span> <span class="c-keyword">and</span> valor <= 85.0:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO"</span>)',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"hospedagem"</span> <span class="c-keyword">and</span> valor <= 450.0:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO"</span>)',
                        '    <span class="c-keyword">else</span>:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Parecer: ANÁLISE DA DIRETORIA"</span>)',
                        '',
                        '<span class="c-keyword">except</span> ValueError:',
                        '    <span class="c-func">print</span>(<span class="c-string">"\\n[ERRO CRÍTICO] O sistema espera um formato numérico (ex: 150.50)."</span>)',
                        '<span class="c-keyword">finally</span>:',
                        '    <span class="c-func">print</span>(<span class="c-string">"\\n[LOG] Sistema de auditoria liberado."</span>)'
                    ])
                },
                {
                    title: 'Versão 3.0: Expansão IA - Persistência de Logs em TXT',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    PROMPT ENVIADO À IA:',
                        '    "Expanda a Versão 2.0. As avaliações estão sendo perdidas após a execução.',
                        '    Adicione a funcionalidade de gravar o resultado da auditoria em um arquivo de',
                        '    texto chamado relatorio_auditoria.txt, preservando o histórico (modo a).',
                        '    Inclua a biblioteca datetime para carimbar a hora do registro."',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-keyword">import</span> datetime',
                        '',
                        '<span class="c-keyword">try</span>:',
                        '    categoria = <span class="c-func">input</span>(<span class="c-string">"Categoria: "</span>).strip().lower()',
                        '    valor = <span class="c-func">float</span>(<span class="c-func">input</span>(<span class="c-string">"Valor (R$): "</span>).replace(<span class="c-string">","</span>, <span class="c-string">"."</span>))',
                        '    ',
                        '    <span class="c-keyword">if</span> valor <= 0:',
                        '        status = <span class="c-string">"NEGADO"</span>',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"transporte"</span> <span class="c-keyword">and</span> valor <= 150.0:',
                        '        status = <span class="c-string">"APROVADO"</span>',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"alimentacao"</span> <span class="c-keyword">and</span> valor <= 85.0:',
                        '        status = <span class="c-string">"APROVADO"</span>',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"hospedagem"</span> <span class="c-keyword">and</span> valor <= 450.0:',
                        '        status = <span class="c-string">"APROVADO"</span>',
                        '    <span class="c-keyword">else</span>:',
                        '        status = <span class="c-string">"ANÁLISE PENDENTE"</span>',
                        '    ',
                        '    <span class="c-func">print</span>(f<span class="c-string">"Resultado em tela: {status}"</span>)',
                        '    ',
                        '    <span class="c-comment"># Abertura e escrita segura em arquivo físico (Persistência)</span>',
                        '    <span class="c-keyword">with</span> <span class="c-func">open</span>(<span class="c-string">"relatorio_auditoria.txt"</span>, <span class="c-string">"a"</span>, encoding=<span class="c-string">"utf-8"</span>) <span class="c-keyword">as</span> arquivo:',
                        '        data_hora = datetime.datetime.now().strftime(<span class="c-string">"%d/%m/%Y %H:%M:%S"</span>)',
                        '        arquivo.write(f<span class="c-string">"[{data_hora}] {categoria.upper()} - R${valor:.2f} -> {status}\\n"</span>)',
                        '        ',
                        '    <span class="c-func">print</span>(<span class="c-string">"-> Log gravado com sucesso no arquivo físico TXT."</span>)',
                        '',
                        '<span class="c-keyword">except</span> ValueError:',
                        '    <span class="c-func">print</span>(<span class="c-string">"[ERRO] Falha de conversão de dados numéricos."</span>)'
                    ])
                },
                {
                    title: 'Versão Final: Empacotamento Desktop (Tkinter)',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    PROMPT ENVIADO À IA:',
                        '    "Para fechar o módulo, construa uma Interface Gráfica nativa usando Tkinter.',
                        '    Como interfaces reagem a eventos (cliques), encapsule a nossa lógica da Versão 3',
                        '    em uma função def validar_despesa() para ser acionada pelo botão do layout."',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-keyword">import</span> tkinter <span class="c-keyword">as</span> tk',
                        '<span class="c-keyword">from</span> tkinter <span class="c-keyword">import</span> messagebox',
                        '<span class="c-keyword">import</span> datetime',
                        '',
                        '<span class="c-comment"># Encapsulamento lógico para integração ao botão</span>',
                        '<span class="c-keyword">def</span> <span class="c-func">validar_despesa</span>():',
                        '    <span class="c-keyword">try</span>:',
                        '        categoria = input_categoria.get().strip().lower()',
                        '        valor = <span class="c-func">float</span>(input_valor.get().replace(<span class="c-string">","</span>, <span class="c-string">"."</span>))',
                        '        ',
                        '        <span class="c-keyword">if</span> valor <= 0:',
                        '            resultado = <span class="c-string">"NEGADO"</span>',
                        '        <span class="c-keyword">elif</span> categoria == <span class="c-string">"transporte"</span> <span class="c-keyword">and</span> valor <= 150.0:',
                        '            resultado = <span class="c-string">"APROVADO"</span>',
                        '        <span class="c-keyword">elif</span> categoria == <span class="c-string">"alimentacao"</span> <span class="c-keyword">and</span> valor <= 85.0:',
                        '            resultado = <span class="c-string">"APROVADO"</span>',
                        '        <span class="c-keyword">elif</span> categoria == <span class="c-string">"hospedagem"</span> <span class="c-keyword">and</span> valor <= 450.0:',
                        '            resultado = <span class="c-string">"APROVADO"</span>',
                        '        <span class="c-keyword">else</span>:',
                        '            resultado = <span class="c-string">"REQUER ANÁLISE"</span>',
                        '        ',
                        '        <span class="c-keyword">with</span> <span class="c-func">open</span>(<span class="c-string">"relatorio_auditoria.txt"</span>, <span class="c-string">"a"</span>, encoding=<span class="c-string">"utf-8"</span>) <span class="c-keyword">as</span> f:',
                        '            data_atual = datetime.datetime.now().strftime(<span class="c-string">"%d/%m/%Y"</span>)',
                        '            f.write(f<span class="c-string">"[{data_atual}] {categoria} - R${valor} -> {resultado}\\n"</span>)',
                        '            ',
                        '        messagebox.showinfo(<span class="c-string">"Sucesso"</span>, f<span class="c-string">"{resultado}\\nLog gerado fisicamente!"</span>)',
                        '        ',
                        '    <span class="c-keyword">except</span> ValueError:',
                        '        messagebox.showerror(<span class="c-string">"Erro"</span>, <span class="c-string">"Preencha o campo de valor apenas com números."</span>)',
                        '',
                        '<span class="c-comment"># Construção Visual</span>',
                        'janela = tk.Tk()',
                        'janela.title(<span class="c-string">"Auditor TechSolutions"</span>)',
                        'janela.geometry(<span class="c-string">"320x220"</span>)',
                        '',
                        'tk.Label(janela, text=<span class="c-string">"Classificação:"</span>).pack(pady=5)',
                        'input_categoria = tk.Entry(janela)',
                        'input_categoria.pack()',
                        '',
                        'tk.Label(janela, text=<span class="c-string">"Valor Emitido (R$):"</span>).pack(pady=5)',
                        'input_valor = tk.Entry(janela)',
                        'input_valor.pack()',
                        '',
                        'btn = tk.Button(janela, text=<span class="c-string">"Processar Compliance"</span>, command=validar_despesa)',
                        'btn.pack(pady=15)',
                        '',
                        'janela.mainloop()'
                    ])
                }
            ]
        }
    ]
};