// Função auxiliar de higienização de string para os blocos de código
const codeStr = (lines) => lines.join('\n');

window.DATA_OFICINA = {
    id: 'oficina',
    title: '2. Mão na Massa',
    icon: 'fa-solid fa-laptop-code',
    content: [
        {
            type: 'card',
            title: '<i class="fa-solid fa-code-branch"></i> Desenvolvimento Orientado',
            html: '<p>Acompanhe a evolução do sistema corporativo. Iniciaremos preparando nossa estação corporativa. Em seguida, desenvolveremos manualmente o "Caminho Feliz", utilizaremos IA para blindar a resiliência (try/except), acoplaremos dados de RH com logs no disco e finalizaremos com uma Interface Desktop munida de Comboboxes, salto automático de cursor, geração de recibos individuais sanitizados e botão de reset.</p>'
        },
        {
            type: 'accordion',
            items: [
                {
                    title: 'Marco Zero: Configuração do Ambiente Corporativo (CPython & VS Code)',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    GUIA DE INFRAESTRUTURA DE DESENVOLVIMENTO (Responsável: Léo)',
                        '    Objetivo: Configurar uma estação de trabalho limpa, padronizada e produtiva.',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># ETAPA 1: INSTALAÇÃO DO INTERPRETADOR OFICIAL (CPYTHON)</span>',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># 1. Acesse o portal oficial: https://www.python.org/downloads/</span>',
                        '<span class="c-comment"># 2. Baixe a versão estável mais recente (Python 3.12+).</span>',
                        '<span class="c-comment"># 3. CRÍTICO NO WINDOWS: Na primeira tela do instalador, marque obrigatoriamente</span>',
                        '<span class="c-comment">#    a caixa "Add python.exe to PATH". Se omitir isso, o terminal falhará.</span>',
                        '',
                        'python --version',
                        '',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># ETAPA 2: INSTALAÇÃO DA IDE (VISUAL STUDIO CODE)</span>',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># Baixe o VS Code: https://code.visualstudio.com/ e marque "Adicionar ao PATH".</span>',
                        '',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># ETAPA 3: EXTENSÕES OBRIGATÓRIAS NO VS CODE</span>',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># Instale o pacote oficial da Microsoft: "Python" (ID: ms-python.python)</span>',
                        '',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># ETAPA 4: DOMINANDO AS EXTENSÕES DE ARQUIVOS</span>',
                        '<span class="c-comment"># ==============================================================================</span>',
                        '<span class="c-comment"># • .py: Scripts estruturados de produção e compilação binária (.exe).</span>',
                        '<span class="c-comment"># • .ipynb: Jupyter Notebooks para prototipagem de IA e Análise de Dados.</span>'
                    ])
                },
                {
                    title: 'PMV 1.0: O "Caminho Feliz" (Execução Sequencial Pura)',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    Desenvolvimento inicial focado exclusivamente na lógica de negócio.',
                        '    Sem tratamento de erros. Se o usuário digitar texto no lugar do valor, o sistema quebra.',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-func">print</span>(<span class="c-string">"=== SISTEMA DE AUDITORIA FINANCEIRA v1.0 ==="</span>)',
                        '<span class="c-func">print</span>(<span class="c-string">"Iniciando captura de dados...\\n"</span>)',
                        '',
                        'categoria_texto = <span class="c-func">input</span>(<span class="c-string">"Digite a categoria (transporte/alimentacao/hospedagem): "</span>)',
                        'categoria = categoria_texto.strip().lower()',
                        '',
                        'valor_texto = <span class="c-func">input</span>(<span class="c-string">"Digite o valor do gasto (R$): "</span>)',
                        'valor_formatado = valor_texto.replace(<span class="c-string">","</span>, <span class="c-string">"."</span>)',
                        '',
                        'valor = <span class="c-func">float</span>(valor_formatado)',
                        '',
                        '<span class="c-func">print</span>(<span class="c-string">"\\nProcessando regras de compliance..."</span>)',
                        '',
                        '<span class="c-keyword">if</span> valor <= 0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: NEGADO - Valor deve ser maior que zero."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"transporte"</span> <span class="c-keyword">and</span> valor <= 150.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO AUTOMATICAMENTE - Dentro do teto de transporte."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"transporte"</span> <span class="c-keyword">and</span> valor > 150.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: REQUER ANÁLISE - Ultrapassou teto de transporte."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"alimentacao"</span> <span class="c-keyword">and</span> valor <= 85.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO AUTOMATICAMENTE - Dentro do teto de alimentação."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"alimentacao"</span> <span class="c-keyword">and</span> valor > 85.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: REQUER ANÁLISE - Ultrapassou teto de alimentação."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"hospedagem"</span> <span class="c-keyword">and</span> valor <= 450.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO AUTOMATICAMENTE - Dentro do teto de hospedagem."</span>)',
                        '<span class="c-keyword">elif</span> categoria == <span class="c-string">"hospedagem"</span> <span class="c-keyword">and</span> valor > 450.0:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: REQUER ANÁLISE - Ultrapassou teto de hospedagem."</span>)',
                        '<span class="c-keyword">else</span>:',
                        '    <span class="c-func">print</span>(<span class="c-string">"Parecer: NEGADO - Categoria não reconhecida."</span>)',
                        '',
                        '<span class="c-func">print</span>(<span class="c-string">"\\nAuditoria finalizada."</span>)'
                    ])
                },
                {
                    title: 'Versão 2.0: Evolução IA - Resiliência e Tratamento de Erros',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    PROMPT ENVIADO À IA:',
                        '    "Atue como Arquiteto Python. O código do PMV 1.0 quebra se o usuário digitar',
                        '    letras no campo de valor monetário. Refatore o código adicionando blocos de',
                        '    tratamento de exceções (try/except/finally) para capturar o erro ValueError',
                        '    e impedir que o sistema feche abruptamente. Otimize levemente os condicionais."',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-func">print</span>(<span class="c-string">"=== SISTEMA DE AUDITORIA FINANCEIRA v2.0 ==="</span>)',
                        '',
                        '<span class="c-keyword">try</span>:',
                        '    categoria = <span class="c-func">input</span>(<span class="c-string">"Categoria (transporte/alimentacao/hospedagem): "</span>).strip().lower()',
                        '    valor_input = <span class="c-func">input</span>(<span class="c-string">"Valor do gasto (R$): "</span>).replace(<span class="c-string">","</span>, <span class="c-string">"."</span>)',
                        '    ',
                        '    valor = <span class="c-func">float</span>(valor_input)',
                        '    ',
                        '    <span class="c-keyword">if</span> valor <= 0:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Parecer: NEGADO - Valor inválido."</span>)',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"transporte"</span> <span class="c-keyword">and</span> valor <= 150.0:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO"</span>)',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"alimentacao"</span> <span class="c-keyword">and</span> valor <= 85.0:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO"</span>)',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"hospedagem"</span> <span class="c-keyword">and</span> valor <= 450.0:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Parecer: APROVADO"</span>)',
                        '    <span class="c-keyword">else</span>:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Parecer: ANÁLISE DA DIRETORIA"</span>)',
                        '',
                        '<span class="c-keyword">except</span> ValueError:',
                        '    <span class="c-func">print</span>(<span class="c-string">"\\n[ERRO CRÍTICO] O sistema espera um formato numérico (ex: 150.50)."</span>)',
                        '<span class="c-keyword">finally</span>:',
                        '    <span class="c-func">print</span>(<span class="c-string">"\\n[LOG] Sistema de auditoria liberado."</span>)'
                    ])
                },
                {
                    title: 'Versão 3.0: Expansão IA - Captura de RH e Log em TXT',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    PROMPT ENVIADO À IA:',
                        '    "Evolua a Versão 2.0. O setor financeiro precisa saber QUEM solicitou o gasto.',
                        '    Adicione a captura sequencial de Nome e Cargo. Antes dos inputs, exiba no console',
                        '    uma tabela explicativa com os tetos limites e os cargos aceitos pela política interna.',
                        '    Grave todos esses novos campos no arquivo relatorio_auditoria.txt (modo a)."',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-keyword">import</span> datetime',
                        '',
                        '<span class="c-comment"># Tabela Informativa Prévia no Terminal</span>',
                        '<span class="c-func">print</span>(<span class="c-string">"======================================================"</span>)',
                        '<span class="c-func">print</span>(<span class="c-string">"        POLÍTICAS INTERNAS DE REEMBOLSO v3.0          "</span>)',
                        '<span class="c-func">print</span>(<span class="c-string">"======================================================"</span>)',
                        '<span class="c-func">print</span>(<span class="c-string">"Categorias e Tetos Máximos:\\n • Transporte: R$ 150.00\\n • Alimentação: R$ 85.00\\n • Hospedagem: R$ 450.00"</span>)',
                        '<span class="c-func">print</span>(<span class="c-string">"\\nCargos Autorizados: Analista, Gerente, Diretor, Técnico"</span>)',
                        '<span class="c-func">print</span>(<span class="c-string">"------------------------------------------------------\\n"</span>)',
                        '',
                        '<span class="c-keyword">try</span>:',
                        '    nome_colaborador = <span class="c-func">input</span>(<span class="c-string">"Nome do Colaborador: "</span>).strip()',
                        '    cargo_colaborador = <span class="c-func">input</span>(<span class="c-string">"Cargo exercido: "</span>).strip().title()',
                        '    categoria = <span class="c-func">input</span>(<span class="c-string">"Categoria da despesa: "</span>).strip().lower()',
                        '    valor = <span class="c-func">float</span>(<span class="c-func">input</span>(<span class="c-string">"Valor emitido na nota (R$): "</span>).replace(<span class="c-string">","</span>, <span class="c-string">"."</span>))',
                        '    ',
                        '    <span class="c-keyword">if</span> valor <= 0:',
                        '        status = <span class="c-string">"NEGADO - Valor zerado"</span>',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"transporte"</span> <span class="c-keyword">and</span> valor <= 150.0:',
                        '        status = <span class="c-string">"APROVADO"</span>',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"alimentacao"</span> <span class="c-keyword">and</span> valor <= 85.0:',
                        '        status = <span class="c-string">"APROVADO"</span>',
                        '    <span class="c-keyword">elif</span> categoria == <span class="c-string">"hospedagem"</span> <span class="c-keyword">and</span> valor <= 450.0:',
                        '        status = <span class="c-string">"APROVADO"</span>',
                        '    <span class="c-keyword">else</span>:',
                        '        status = <span class="c-string">"ANÁLISE PENDENTE DA DIRETORIA"</span>',
                        '    ',
                        '    <span class="c-func">print</span>(f<span class="c-string">"\\nParecer Emitido -> {nome_colaborador} ({cargo_colaborador}): {status}"</span>)',
                        '    ',
                        '    <span class="c-keyword">with</span> <span class="c-func">open</span>(<span class="c-string">"relatorio_auditoria.txt"</span>, <span class="c-string">"a"</span>, encoding=<span class="c-string">"utf-8"</span>) <span class="c-keyword">as</span> arquivo:',
                        '        carimbo = datetime.datetime.now().strftime(<span class="c-string">"%d/%m/%Y %H:%M"</span>)',
                        '        linha = f<span class="c-string">"[{carimbo}] NOME: {nome_colaborador} | CARGO: {cargo_colaborador} | CAT: {categoria.upper()} | VAL: R${valor:.2f} -> {status}\\n"</span>',
                        '        arquivo.write(linha)',
                        '        ',
                        '    <span class="c-func">print</span>(<span class="c-string">"-> Registro administrativo salvo com sucesso no arquivo TXT."</span>)',
                        '',
                        '<span class="c-keyword">except</span> ValueError:',
                        '    <span class="c-func">print</span>(<span class="c-string">"[ERRO] Falha na conversão de caracteres do campo monetário."</span>)'
                    ])
                },
                {
                    title: 'Versão Final: Desktop Corporativo Completo (Tkinter ERP)',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    PROMPT ENVIADO À IA:',
                        '    "Abstraia o sistema para uma Interface Gráfica nativa Tkinter de nível empresarial.',
                        '    1) Utilize ttk.Combobox para Cargos e Categorias;',
                        '    2) Ao selecionar a Categoria, engatilhe o evento virtual <<ComboboxSelected>> para',
                        '       saltar o cursor automaticamente ao campo Valor Gasto;',
                        '    3) Cada reembolso deve gerar um arquivo .txt individual sob o template',
                        '       Nome_Cargo_DD-MM-AAAA_timestamp.txt (sanitizado contra erros do Windows);',
                        '    4) Mantenha a gravação no log geral para o botão Ver Todos (.txt) abrir o notepad;',
                        '    5) Crie o botão Finalizar Pedido / Limpar Tela que resete todo o formulário."',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-keyword">import</span> tkinter <span class="c-keyword">as</span> tk',
                        '<span class="c-keyword">from</span> tkinter <span class="c-keyword">import</span> ttk, messagebox',
                        '<span class="c-keyword">import</span> datetime',
                        '<span class="c-keyword">import</span> time',
                        '<span class="c-keyword">import</span> os',
                        '',
                        'tetos_rh = {<span class="c-string">"Transporte"</span>: 150.0, <span class="c-string">"Alimentação"</span>: 85.0, <span class="c-string">"Hospedagem"</span>: 450.0}',
                        'lista_cargos = [<span class="c-string">"Analista de TI"</span>, <span class="c-string">"Desenvolvedor"</span>, <span class="c-string">"Gerente de Projetos"</span>, <span class="c-string">"Suporte Técnico"</span>]',
                        '',
                        '<span class="c-comment"># Callback de Salto Automático de Foco</span>',
                        '<span class="c-keyword">def</span> <span class="c-func">ao_selecionar_categoria</span>(event):',
                        '    input_valor.focus()',
                        '',
                        '<span class="c-keyword">def</span> <span class="c-func">processar_reembolso</span>():',
                        '    <span class="c-keyword">try</span>:',
                        '        nome = input_nome.get().strip()',
                        '        cargo = cb_cargo.get()',
                        '        cat = cb_categoria.get()',
                        '        val_str = input_valor.get().replace(<span class="c-string">","</span>, <span class="c-string">"."</span>)',
                        '        ',
                        '        <span class="c-keyword">if not</span> nome <span class="c-keyword">or not</span> cargo <span class="c-keyword">or not</span> cat:',
                        '            messagebox.showwarning(<span class="c-string">"Atenção"</span>, <span class="c-string">"Preencha todos os dados de identificação."</span>)',
                        '            <span class="c-keyword">return</span>',
                        '            ',
                        '        valor = <span class="c-func">float</span>(val_str)',
                        '        teto = tetos_rh.get(cat, 0.0)',
                        '        parecer = <span class="c-string">"APROVADO"</span> <span class="c-keyword">if</span> (valor > 0 <span class="c-keyword">and</span> valor <= teto) <span class="c-keyword">else</span> <span class="c-string">"RETIDO / ANÁLISE"</span>',
                        '        ',
                        '        <span class="c-comment"># 1. Gerando Arquivo Individual Sanitizado</span>',
                        '        agora = datetime.datetime.now()',
                        '        data_arquivo = agora.strftime(<span class="c-string">"%d-%m-%Y"</span>)',
                        '        data_tela = agora.strftime(<span class="c-string">"%d/%m/%Y às %H:%M:%S"</span>)',
                        '        data_master = agora.strftime(<span class="c-string">"%d/%m %H:%M"</span>)',
                        '        timestamp_unix = <span class="c-func">int</span>(time.time())',
                        '        ',
                        '        nome_limpo = <span class="c-string">""</span>.join(c <span class="c-keyword">for</span> c <span class="c-keyword">in</span> nome <span class="c-keyword">if</span> c.isalnum())',
                        '        cargo_limpo = <span class="c-string">""</span>.join(c <span class="c-keyword">for</span> c <span class="c-keyword">in</span> cargo <span class="c-keyword">if</span> c.isalnum())',
                        '        nome_arquivo = f<span class="c-string">"{nome_limpo}_{cargo_limpo}_{data_arquivo}_{timestamp_unix}.txt"</span>',
                        '        ',
                        '        conteudo_recibo = (',
                        '            f<span class="c-string">"=========================================\\n"</span>',
                        '            f<span class="c-string">"      COMPROVANTE DE REEMBOLSO INDIVIDUAL\\n"</span>',
                        '            f<span class="c-string">"=========================================\\n"</span>',
                        '            f<span class="c-string">"Registro: {data_tela}\\n"</span>',
                        '            f<span class="c-string">"Colaborador: {nome}\\n"</span>',
                        '            f<span class="c-string">"Cargo: {cargo}\\n"</span>',
                        '            f<span class="c-string">"Categoria Solicitada: {cat}\\n"</span>',
                        '            f<span class="c-string">"Valor Solicitado: R$ {valor:.2f}\\n"</span>',
                        '            f<span class="c-string">"Parecer de Compliance: {parecer}\\n"</span>',
                        '            f<span class="c-string">"=========================================\\n"</span>',
                        '        )',
                        '        ',
                        '        <span class="c-keyword">with</span> <span class="c-func">open</span>(nome_arquivo, <span class="c-string">"w"</span>, encoding=<span class="c-string">"utf-8"</span>) <span class="c-keyword">as</span> f_ind:',
                        '            f_ind.write(conteudo_recibo)',
                        '            ',
                        '        <span class="c-comment"># 2. Alimentando Log Master</span>',
                        '        linha_master = f<span class="c-string">"[{data_master}] {nome} ({cargo}) | {cat}: R${valor:.2f} -> {parecer} [Arquivo: {nome_arquivo}]\\n"</span>',
                        '        <span class="c-keyword">with</span> <span class="c-func">open</span>(<span class="c-string">"relatorio_auditoria.txt"</span>, <span class="c-string">"a"</span>, encoding=<span class="c-string">"utf-8"</span>) <span class="c-keyword">as</span> f_master:',
                        '            f_master.write(linha_master)',
                        '            ',
                        '        lista_sessao.insert(tk.END, f<span class="c-string">"• {nome.split()[0]}: R${valor:.2f} ({parecer})"</span>)',
                        '        messagebox.showinfo(<span class="c-string">"Registrado"</span>, f<span class="c-string">"Sucesso!\\nRecibo isolado gerado:\\n{nome_arquivo}"</span>)',
                        '        ',
                        '        <span class="c-comment"># Reset Parcial Inteligente (Preserva Nome e Cargo)</span>',
                        '        cb_categoria.set(<span class="c-string">""</span>)',
                        '        input_valor.delete(0, tk.END)',
                        '        cb_categoria.focus()',
                        '        ',
                        '    <span class="c-keyword">except</span> ValueError:',
                        '        messagebox.showerror(<span class="c-string">"Erro"</span>, <span class="c-string">"Insira valores monetários numéricos."</span>)',
                        '',
                        '<span class="c-keyword">def</span> <span class="c-func">limpar_formulario</span>():',
                        '    input_nome.delete(0, tk.END)',
                        '    cb_cargo.set(<span class="c-string">""</span>)',
                        '    cb_categoria.set(<span class="c-string">""</span>)',
                        '    input_valor.delete(0, tk.END)',
                        '    input_nome.focus()',
                        '',
                        '<span class="c-keyword">def</span> <span class="c-func">abrir_bloco_notas</span>():',
                        '    <span class="c-keyword">if</span> os.path.exists(<span class="c-string">"relatorio_auditoria.txt"</span>):',
                        '        os.startfile(<span class="c-string">"relatorio_auditoria.txt"</span>)',
                        '    <span class="c-keyword">else</span>:',
                        '        messagebox.showinfo(<span class="c-string">"Vazio"</span>, <span class="c-string">"Nenhum registro foi gerado no disco ainda."</span>)',
                        '',
                        '<span class="c-comment"># Construção Visual do ERP</span>',
                        'app = tk.Tk()',
                        'app.title(<span class="c-string">"TechSolutions ERP v5.0"</span>)',
                        'app.geometry(<span class="c-string">"380x510"</span>)',
                        'app.configure(padx=20, pady=15)',
                        '',
                        'tk.Label(app, text=<span class="c-string">"Nome do Colaborador:"</span>, font=(<span class="c-string">"Inter"</span>, 9, <span class="c-string">"bold"</span>)).pack(anchor=<span class="c-string">"w"</span>)',
                        'input_nome = tk.Entry(app, width=42)',
                        'input_nome.pack(pady=(2, 8))',
                        '',
                        'tk.Label(app, text=<span class="c-string">"Cargo Exercido:"</span>, font=(<span class="c-string">"Inter"</span>, 9, <span class="c-string">"bold"</span>)).pack(anchor=<span class="c-string">"w"</span>)',
                        'cb_cargo = ttk.Combobox(app, values=lista_cargos, state=<span class="c-string">"readonly"</span>, width=39)',
                        'cb_cargo.pack(pady=(2, 8))',
                        '',
                        'tk.Label(app, text=<span class="c-string">"Categoria da Despesa:"</span>, font=(<span class="c-string">"Inter"</span>, 9, <span class="c-string">"bold"</span>)).pack(anchor=<span class="c-string">"w"</span>)',
                        'cb_categoria = ttk.Combobox(app, values=list(tetos_rh.keys()), state=<span class="c-string">"readonly"</span>, width=39)',
                        'cb_categoria.pack(pady=(2, 8))',
                        '',
                        '<span class="c-comment"># LINHA CRÍTICA DO BIND CORRIGIDA AQUI:</span>',
                        'cb_categoria.bind(<span class="c-string">"&lt;&lt;ComboboxSelected&gt;&gt;"</span>, ao_selecionar_categoria)',
                        '',
                        'tk.Label(app, text=<span class="c-string">"Valor Gasto (R$):"</span>, font=(<span class="c-string">"Inter"</span>, 9, <span class="c-string">"bold"</span>)).pack(anchor=<span class="c-string">"w"</span>)',
                        'input_valor = tk.Entry(app, width=42)',
                        'input_valor.pack(pady=(2, 12))',
                        '',
                        'tk.Button(app, text=<span class="c-string">"Registrar Reembolso"</span>, command=processar_reembolso, bg=<span class="c-string">"#ea580c"</span>, fg=<span class="c-string">"white"</span>, font=(<span class="c-string">"Inter"</span>, 9, <span class="c-string">"bold"</span>), relief=<span class="c-string">"flat"</span>).pack(fill=<span class="c-string">"x"</span>, pady=3)',
                        'tk.Button(app, text=<span class="c-string">"Finalizar Pedido / Limpar Tela"</span>, command=limpar_formulario, bg=<span class="c-string">"#64748b"</span>, fg=<span class="c-string">"white"</span>, font=(<span class="c-string">"Inter"</span>, 9, <span class="c-string">"bold"</span>), relief=<span class="c-string">"flat"</span>).pack(fill=<span class="c-string">"x"</span>, pady=3)',
                        'tk.Button(app, text=<span class="c-string">"Ver Todos os Registros (.txt)"</span>, command=abrir_bloco_notas, bg=<span class="c-string">"#2563eb"</span>, fg=<span class="c-string">"white"</span>, relief=<span class="c-string">"flat"</span>).pack(fill=<span class="c-string">"x"</span>, pady=3)',
                        '',
                        'tk.Label(app, text=<span class="c-string">"--- Registros Inseridos na Sessão ---"</span>, font=(<span class="c-string">"Inter"</span>, 8, <span class="c-string">"italic"</span>), fg=<span class="c-string">"#64748b"</span>).pack(pady=(12, 4))',
                        'lista_sessao = tk.Listbox(app, height=4, width=48, font=(<span class="c-string">"Courier New"</span>, 8), bg=<span class="c-string">"#f8fafc"</span>, borderwidth=1)',
                        'lista_sessao.pack()',
                        '',
                        'app.mainloop()'
                    ])
                }
            ]
        }
    ]
};