// Função auxiliar de higienização de string para os blocos de código
const codeStr = (lines) => lines.join('\n');

window.DATA_OFICINA = {
    id: 'oficina',
    title: '2. Mão na Massa',
    icon: 'fa-solid fa-laptop-code',
    content: [
        {
            type: 'card',
            title: '<i class="fa-solid fa-code-branch"></i> Evolução Didática',
            html: '<p>Acompanhe a progressão arquitetural. Iniciaremos com um laço contínuo simples no console ("Caminho Feliz"), evoluiremos com Inteligência Artificial para um Menu Operacional resiliente, anexaremos exportação dupla (CSV/JSON) e daremos o grande salto transformando o script em um Web App reativo.</p>'
        },
        {
            type: 'accordion',
            items: [
                {
                    title: 'PMV 1.0: O "Caminho Feliz" (Laço While no Console)',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    PMV 1.0 - Processador Contínuo de Folha de Pagamento',
                        '    Conceito: Introdução ao laço \'while True\' e acumuladores de estado na memória.',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-func">print</span>(<span class="c-string">"=== PROCESSADOR DE FOLHA TECHSOLUTIONS v1.0 ==="</span>)',
                        '',
                        '<span class="c-comment"># Variável Acumuladora (Mantém o estado fora do ciclo)</span>',
                        'total_folha = 0.0',
                        '',
                        '<span class="c-comment"># Laço infinito: O código recomeça aqui automaticamente</span>',
                        '<span class="c-keyword">while True</span>:',
                        '    nome = <span class="c-func">input</span>(<span class="c-string">"\\nNome do Colaborador: "</span>).strip()',
                        '    salario_base = <span class="c-func">float</span>(<span class="c-func">input</span>(<span class="c-string">"Salário Base (R$): "</span>))',
                        '    bonus = <span class="c-func">float</span>(<span class="c-func">input</span>(<span class="c-string">"Bônus de Meta (R$): "</span>))',
                        '    ',
                        '    salario_final = salario_base + bonus',
                        '    total_folha += salario_final <span class="c-comment"># Somando ao acumulador global</span>',
                        '    ',
                        '    <span class="c-func">print</span>(f<span class="c-string">"-> Holerite calculado: {nome} | Líquido: R$ {salario_final:.2f}"</span>)',
                        '    ',
                        '    <span class="c-comment"># Condição de Parada do Ciclo</span>',
                        '    continuar = <span class="c-func">input</span>(<span class="c-string">"Deseja processar outro colaborador? [S/N]: "</span>).strip().upper()',
                        '    <span class="c-keyword">if</span> continuar == <span class="c-string">"N"</span>:',
                        '        <span class="c-keyword">break</span> <span class="c-comment"># Quebra e encerra o laço \'while\' imediatamente</span>',
                        '',
                        '<span class="c-func">print</span>(f<span class="c-string">"\\n=== FECHAMENTO DO LOTE ===\\nTotal Acumulado na Folha: R$ {total_folha:.2f}"</span>)'
                    ])
                },
                {
                    title: 'Versão 2.0: Evolução IA - Menu Operacional e Tratamento no Ciclo',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    PROMPT ENVIADO À IA:',
                        '    "Refatore o PMV 1.0. Substitua a pergunta [S/N] por um Menu Numérico no terminal:',
                        '    [1] Cadastrar Colaborador | [2] Ver Total Acumulado | [3] Encerrar Sistema.',
                        '    Envolva a captura matemática num try/except dentro do loop para impedir que',
                        '    digitações erradas encerrem o lote inteiro da folha de pagamento."',
                        '\'\'\'</span>',
                        '',
                        'total_folha = 0.0',
                        'total_colaboradores = 0',
                        '',
                        '<span class="c-keyword">while True</span>:',
                        '    <span class="c-func">print</span>(<span class="c-string">"\\n-----------------------------------"</span>)',
                        '    <span class="c-func">print</span>(<span class="c-string">" 1. Adicionar Holerite ao Lote     "</span>)',
                        '    <span class="c-func">print</span>(<span class="c-string">" 2. Exibir Parcial da Sessão       "</span>)',
                        '    <span class="c-func">print</span>(<span class="c-string">" 3. Fechar Folha e Sair            "</span>)',
                        '    opcao = <span class="c-func">input</span>(<span class="c-string">"Escolha uma operação: "</span>).strip()',
                        '    ',
                        '    <span class="c-keyword">if</span> opcao == <span class="c-string">"1"</span>:',
                        '        <span class="c-keyword">try</span>:',
                        '            nome = <span class="c-func">input</span>(<span class="c-string">"Colaborador: "</span>).strip()',
                        '            valor = <span class="c-func">float</span>(<span class="c-func">input</span>(<span class="c-string">"Valor Total a Pagar (R$): "</span>).replace(<span class="c-string">","</span>, <span class="c-string">"."</span>))',
                        '            <span class="c-keyword">if</span> valor <= 0:',
                        '                <span class="c-func">print</span>(<span class="c-string">"[ERRO] O valor deve ser positivo."</span>)',
                        '                <span class="c-keyword">continue</span> <span class="c-comment"># Pula o resto do laço e volta pro início do Menu</span>',
                        '                ',
                        '            total_folha += valor',
                        '            total_colaboradores += 1',
                        '            <span class="c-func">print</span>(<span class="c-string">"-> Holerite contabilizado com sucesso!"</span>)',
                        '            ',
                        '        <span class="c-keyword">except</span> ValueError:',
                        '            <span class="c-func">print</span>(<span class="c-string">"[FALHA] Digite apenas números monetários."</span>)',
                        '            ',
                        '    <span class="c-keyword">elif</span> opcao == <span class="c-string">"2"</span>:',
                        '        <span class="c-func">print</span>(f<span class="c-string">"\\n[PARCIAL] Registros: {total_colaboradores} | Montante: R$ {total_folha:.2f}"</span>)',
                        '        ',
                        '    <span class="c-keyword">elif</span> opcao == <span class="c-string">"3"</span>:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Encerrando lote..."</span>)',
                        '        <span class="c-keyword">break</span>',
                        '    <span class="c-keyword">else</span>:',
                        '        <span class="c-func">print</span>(<span class="c-string">"Opção inválida!"</span>)'
                    ])
                },
                {
                    title: 'Versão 3.0: Persistência Dupla Corporativa (.CSV e .JSON)',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    PROMPT ENVIADO À IA:',
                        '    "Evolua a Versão 2.0. Salve cada holerite processado simultaneamente em:',
                        '    1) Um arquivo folha_lote.csv (usando a biblioteca nativa csv);',
                        '    2) Um arquivo folha_lote.json (acumulando registros numa lista de dicionários).',
                        '    Mantenha a estrutura sequencial dentro do laço while."',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-keyword">import</span> csv',
                        '<span class="c-keyword">import</span> json',
                        '<span class="c-keyword">import</span> os',
                        '',
                        'arquivo_json = <span class="c-string">"folha_lote.json"</span>',
                        'arquivo_csv = <span class="c-string">"folha_lote.csv"</span>',
                        '',
                        '<span class="c-comment"># Criando cabeçalho do CSV se o arquivo não existir</span>',
                        '<span class="c-keyword">if not</span> os.path.exists(arquivo_csv):',
                        '    <span class="c-keyword">with</span> <span class="c-func">open</span>(arquivo_csv, <span class="c-string">"w"</span>, newline=<span class="c-string">""</span>, encoding=<span class="c-string">"utf-8"</span>) <span class="c-keyword">as</span> f_csv:',
                        '        writer = csv.writer(f_csv)',
                        '        writer.writerow([<span class="c-string">"Nome"</span>, <span class="c-string">"Cargo"</span>, <span class="c-string">"ValorPago"</span>])',
                        '',
                        '<span class="c-keyword">while True</span>:',
                        '    nome = <span class="c-func">input</span>(<span class="c-string">"\\nNome (ou digite SAIR para encerrar): "</span>).strip()',
                        '    <span class="c-keyword">if</span> nome.upper() == <span class="c-string">"SAIR"</span>:',
                        '        <span class="c-keyword">break</span>',
                        '        ',
                        '    cargo = <span class="c-func">input</span>(<span class="c-string">"Cargo: "</span>).strip()',
                        '    <span class="c-keyword">try</span>:',
                        '        valor = <span class="c-func">float</span>(<span class="c-func">input</span>(<span class="c-string">"Valor a Pagar (R$): "</span>).replace(<span class="c-string">","</span>, <span class="c-string">"."</span>))',
                        '        ',
                        '        <span class="c-comment"># 1. Gravando no CSV</span>',
                        '        <span class="c-keyword">with</span> <span class="c-func">open</span>(arquivo_csv, <span class="c-string">"a"</span>, newline=<span class="c-string">""</span>, encoding=<span class="c-string">"utf-8"</span>) <span class="c-keyword">as</span> f_csv:',
                        '            csv.writer(f_csv).writerow([nome, cargo, valor])',
                        '            ',
                        '        <span class="c-comment"># 2. Gravando no JSON</span>',
                        '        lista_dados = []',
                        '        <span class="c-keyword">if</span> os.path.exists(arquivo_json):',
                        '            <span class="c-keyword">with</span> <span class="c-func">open</span>(arquivo_json, <span class="c-string">"r"</span>, encoding=<span class="c-string">"utf-8"</span>) <span class="c-keyword">as</span> f_json:',
                        '                lista_dados = json.load(f_json)',
                        '                ',
                        '        lista_dados.append({<span class="c-string">"colaborador"</span>: nome, <span class="c-string">"cargo"</span>: cargo, <span class="c-string">"liquido"</span>: valor})',
                        '        ',
                        '        <span class="c-keyword">with</span> <span class="c-func">open</span>(arquivo_json, <span class="c-string">"w"</span>, encoding=<span class="c-string">"utf-8"</span>) <span class="c-keyword">as</span> f_json:',
                        '            json.dump(lista_dados, f_json, indent=4, ensure_ascii=<span class="c-keyword">False</span>)',
                        '            ',
                        '        <span class="c-func">print</span>(<span class="c-string">"-> Salvo em CSV e JSON com sucesso!"</span>)',
                        '    <span class="c-keyword">except</span> ValueError:',
                        '        <span class="c-func">print</span>(<span class="c-string">"[ERRO] Numeral incorreto."</span>)'
                    ])
                },
                {
                    title: 'Versão Final: Salto Arquitetural — Web App Reativo (Streamlit)',
                    code: codeStr([
                        '<span class="c-comment">\'\'\'',
                        '    PROMPT ENVIADO À IA:',
                        '    Abstraia o sistema de folha para um Web App moderno usando o framework Streamlit.',
                        '    1) Utilize st.session_state para acumular a lista de holerites na sessão Web;',
                        '    2) Monte um formulário lateral (sidebar) para inserção de Colaborador, Cargo e Valor;',
                        '    3) Exiba os dados consolidados em uma tabela dinâmica interativa (st.dataframe);',
                        '    4) Disponibilize botões nativos de Download para exportar a folha em CSV e JSON.',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-comment">\'\'\'',
                        '    CRÍTICO DE EXECUÇÃO: Aplicações Streamlit NÃO rodam com o comando padrão python.',
                        '    Para inicializar o servidor Web dinâmico, digite no terminal do VS Code:',
                        '    -> python -m streamlit run folha_pagamento_web.py',
                        '\'\'\'</span>',
                        '',
                        '<span class="c-keyword">import</span> streamlit <span class="c-keyword">as</span> st',
                        '<span class="c-keyword">import</span> pandas <span class="c-keyword">as</span> pd',
                        '<span class="c-keyword">import</span> json',
                        '',
                        'st.set_page_config(page_title=<span class="c-string">"TechSolutions Folha Web"</span>, page_icon=<span class="c-string">"💼"</span>, layout=<span class="c-string">"wide"</span>)',
                        '',
                        '<span class="c-comment"># Inicializando memória de sessão reativa no navegador</span>',
                        '<span class="c-keyword">if</span> <span class="c-string">"lote_folha"</span> <span class="c-keyword">not in</span> st.session_state:',
                        '    st.session_state[<span class="c-string">"lote_folha"</span>] = []',
                        '',
                        '<span class="c-comment"># Título corrigido conforme solicitação</span>',
                        'st.title(<span class="c-string">"💼 Sistema de Processamento de Folha Web"</span>)',
                        'st.markdown(<span class="c-string">"Ambiente corporativo de auditoria e exportação em lote."</span>)',
                        '',
                        '<span class="c-comment"># Formulário Lateral</span>',
                        '<span class="c-keyword">with</span> st.sidebar.form(key=<span class="c-string">"form_holerite"</span>, clear_on_submit=<span class="c-keyword">True</span>):',
                        '    st.header(<span class="c-string">"➕ Novo Holerite"</span>)',
                        '    nome = st.text_input(<span class="c-string">"Nome do Colaborador"</span>)',
                        '    cargo = st.selectbox(<span class="c-string">"Cargo"</span>, [<span class="c-string">"Analista"</span>, <span class="c-string">"Desenvolvedor"</span>, <span class="c-string">"Gerente"</span>, <span class="c-string">"Diretor"</span>])',
                        '    valor = st.number_input(<span class="c-string">"Salário Líquido (R$)"</span>, min_value=0.0, step=100.0)',
                        '    submit = st.form_submit_button(<span class="c-string">"Adicionar ao Lote"</span>)',
                        '    ',
                        '    <span class="c-keyword">if</span> submit <span class="c-keyword">and</span> nome <span class="c-keyword">and</span> valor > 0:',
                        '        st.session_state[<span class="c-string">"lote_folha"</span>].append({<span class="c-string">"Colaborador"</span>: nome, <span class="c-string">"Cargo"</span>: cargo, <span class="c-string">"Líquido (R$)"</span>: valor})',
                        '        st.success(f<span class="c-string">"{nome} adicionado!"</span>)',
                        '',
                        '<span class="c-comment"># Renderização Principal</span>',
                        '<span class="c-keyword">if</span> st.session_state[<span class="c-string">"lote_folha"</span>]:',
                        '    df = pd.DataFrame(st.session_state[<span class="c-string">"lote_folha"</span>])',
                        '    ',
                        '    col1, col2 = st.columns(2)',
                        '    col1.metric(<span class="c-string">"Colaboradores no Lote"</span>, <span class="c-func">len</span>(df))',
                        '    col2.metric(<span class="c-string">"Montante Total da Folha"</span>, f<span class="c-string">"R$ {df[\'Líquido (R$)\'].sum():,.2f}"</span>)',
                        '    ',
                        '    st.subheader(<span class="c-string">"📑 Base Consolidada"</span>)',
                        '    st.dataframe(df, use_container_width=<span class="c-keyword">True</span>)',
                        '    ',
                        '    <span class="c-comment"># Exportação Web Dinâmica</span>',
                        '    csv_buffer = df.to_csv(index=<span class="c-keyword">False</span>).encode(<span class="c-string">"utf-8"</span>)',
                        '    json_buffer = json.dumps(st.session_state[<span class="c-string">"lote_folha"</span>], indent=4, ensure_ascii=<span class="c-keyword">False</span>).encode(<span class="c-string">"utf-8"</span>)',
                        '    ',
                        '    d1, d2 = st.columns(2)',
                        '    d1.download_button(<span class="c-string">"📥 Baixar Lote (.CSV)"</span>, data=csv_buffer, file_name=<span class="c-string">"folha.csv"</span>, mime=<span class="c-string">"text/csv"</span>, use_container_width=<span class="c-keyword">True</span>)',
                        '    d2.download_button(<span class="c-string">"📥 Baixar Lote (.JSON)"</span>, data=json_buffer, file_name=<span class="c-string">"folha.json"</span>, mime=<span class="c-string">"application/json"</span>, use_container_width=<span class="c-keyword">True</span>)',
                        '<span class="c-keyword">else</span>:',
                        '    st.info(<span class="c-string">"👈 Utilize a barra lateral esquerda para cadastrar o primeiro holerite da folha."</span>)'
                    ])
                }
            ]
        }
    ]
};